<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ControlCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lookupTables = [
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'PEMOHON',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'05',
                'CTL_CTRLNAMA' =>'ATL',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'06',
                'CTL_CTRLNAMA' =>'BTD',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'B',
                'CTL_CTRLNAMA' =>'PERMOHONAN BARU',
                'CTL_CTRLGRP' =>'JENIS_MHN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'R',
                'CTL_CTRLNAMA' =>'PEMBAHARUAN LESEN',
                'CTL_CTRLGRP' =>'JENIS_MHN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'DISCOUNT ATAS AMAUN',
                'CTL_CTRLGRP' =>'DISCOUNT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'DISCOUNT ATAS PERATUS',
                'CTL_CTRLGRP' =>'DISCOUNT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'TIADA DISCOUNT',
                'CTL_CTRLGRP' =>'DISCOUNT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'R',
                'CTL_CTRLNAMA' =>'RISIKO RENDAH\/TIADA RISIKO',
                'CTL_CTRLGRP' =>'RISIKO',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'T',
                'CTL_CTRLNAMA' =>'RISIKO TINGGI',
                'CTL_CTRLGRP' =>'RISIKO',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'K',
                'CTL_CTRLNAMA' =>'RISIKO TINGGI\/KRITIKAL\/SENSITIF',
                'CTL_CTRLGRP' =>'RISIKO',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'KPKT',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'JKT',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'04',
                'CTL_CTRLNAMA' =>'PBT',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MBI',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'ZON MERU',
                'CTL_CTRLGRP' =>'ATL_BOMBA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MBI',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'ZON BANDAR',
                'CTL_CTRLGRP' =>'ATL_BOMBA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'NO. SSM',
                'CTL_CTRLGRP' =>'JENIS_PLG',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'04',
                'CTL_CTRLNAMA' =>'NO. PASSPORT',
                'CTL_CTRLGRP' =>'JENIS_PLG',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'NO.KP BARU',
                'CTL_CTRLGRP' =>'JENIS_PLG',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'NO.KP LAMA',
                'CTL_CTRLGRP' =>'JENIS_PLG',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'05',
                'CTL_CTRLNAMA' =>'NO POLIS',
                'CTL_CTRLGRP' =>'JENIS_PLG',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'Apa Warna Kegemaran ?',
                'CTL_CTRLGRP' =>'SOALAN_SAH',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'OTP',
                'CTL_CTRLGRP' =>'KAEDAH_SAH',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'KYC',
                'CTL_CTRLGRP' =>'KAEDAH_SAH',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'Siapa Nama Ibu ?',
                'CTL_CTRLGRP' =>'SOALAN_SAH',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'MPKK',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'Makanan Kegemaran ?',
                'CTL_CTRLGRP' =>'SOALAN_SAH',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'M',
                'CTL_CTRLNAMA' =>'MELAYU',
                'CTL_CTRLGRP' =>'BANGSA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'C',
                'CTL_CTRLNAMA' =>'CHINA',
                'CTL_CTRLGRP' =>'BANGSA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'I',
                'CTL_CTRLNAMA' =>'INDIA',
                'CTL_CTRLGRP' =>'BANGSA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'L',
                'CTL_CTRLNAMA' =>'LAIN-LAIN',
                'CTL_CTRLGRP' =>'BANGSA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'I',
                'CTL_CTRLNAMA' =>'ISLAM',
                'CTL_CTRLGRP' =>'AGAMA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'B',
                'CTL_CTRLNAMA' =>'BUDDHA',
                'CTL_CTRLGRP' =>'AGAMA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'H',
                'CTL_CTRLNAMA' =>'HINDU',
                'CTL_CTRLGRP' =>'AGAMA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'K',
                'CTL_CTRLNAMA' =>'KRISTIAN',
                'CTL_CTRLGRP' =>'AGAMA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'K',
                'CTL_CTRLNAMA' =>'BERKAHWIN',
                'CTL_CTRLGRP' =>'KAHWIN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'B',
                'CTL_CTRLNAMA' =>'BUJANG',
                'CTL_CTRLGRP' =>'KAHWIN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'I',
                'CTL_CTRLNAMA' =>'JANDA',
                'CTL_CTRLGRP' =>'KAHWIN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'K',
                'CTL_CTRLNAMA' =>'DUDA',
                'CTL_CTRLGRP' =>'KAHWIN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'L',
                'CTL_CTRLNAMA' =>'LELAKI',
                'CTL_CTRLGRP' =>'JANTINA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'P',
                'CTL_CTRLNAMA' =>'PEREMPUAN',
                'CTL_CTRLGRP' =>'JANTINA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'T',
                'CTL_CTRLNAMA' =>'TETAP',
                'CTL_CTRLGRP' =>'STATUS_KMT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'K',
                'CTL_CTRLNAMA' =>'KONTRAK',
                'CTL_CTRLGRP' =>'STATUS_KMT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'S',
                'CTL_CTRLNAMA' =>'SAMBILAN',
                'CTL_CTRLGRP' =>'STATUS_KMT',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'J',
                'CTL_CTRLNAMA' =>'JABATAN',
                'CTL_CTRLGRP' =>'KELAS_PTJ',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'B',
                'CTL_CTRLNAMA' =>'BAHAGIAN',
                'CTL_CTRLGRP' =>'KELAS_PTJ',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'U',
                'CTL_CTRLNAMA' =>'UNIT',
                'CTL_CTRLGRP' =>'KELAS_PTJ',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'1',
                'CTL_CTRLNAMA' =>'BANDAR',
                'CTL_CTRLGRP' =>'KAT_NIAGA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'2',
                'CTL_CTRLNAMA' =>'LUAR BANDAR',
                'CTL_CTRLGRP' =>'KAT_NIAGA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'3',
                'CTL_CTRLNAMA' =>'LAIN-LAIN',
                'CTL_CTRLGRP' =>'KAT_NIAGA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'D',
                'CTL_CTRLNAMA' =>'PERKHIDMATAN',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'C',
                'CTL_CTRLNAMA' =>'PEMBANGUNAN',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'B',
                'CTL_CTRLNAMA' =>'KEMUDAHAN AWAM',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'A',
                'CTL_CTRLNAMA' =>'ALAM SEKITAR',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'E',
                'CTL_CTRLNAMA' =>'LAIN-LAIN',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'F',
                'CTL_CTRLNAMA' =>'ADUAN BERULANG',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'G',
                'CTL_CTRLNAMA' =>'PENGURUSAN HARTA',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>7,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'P',
                'CTL_CTRLNAMA' =>'BUKAN TEKNIKAL',
                'CTL_CTRLGRP' =>'KAT_ADUAN',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>8,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'1',
                'CTL_CTRLNAMA' =>'BANKRAP',
                'CTL_CTRLGRP' =>'LISTHITAM',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>'CSM_ZUBAIRI',
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>'2025-12-24',
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'2',
                'CTL_CTRLNAMA' =>'GILA',
                'CTL_CTRLGRP' =>'LISTHITAM',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>'CSM_ZUBAIRI',
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>'2025-12-24',
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'PRK_MDTM',
                'CTL_CTRLCODE' =>'3',
                'CTL_CTRLNAMA' =>'HUTANG MELEBIHI LIMIT DITETAPKAN',
                'CTL_CTRLGRP' =>'LISTHITAM',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>'CSM_ZUBAIRI',
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>'2025-12-24',
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'LULUS',
                'CTL_CTRLGRP' =>'MOHON',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'GAGAL',
                'CTL_CTRLGRP' =>'MOHON',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'SEMAKAN',
                'CTL_CTRLGRP' =>'MOHON',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'82',
                'CTL_CTRLNAMA' =>'NEGERI TIDAK DIKETAHUI',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>1,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'08',
                'CTL_CTRLNAMA' =>'PERAK DARUL RIDZUAN',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>2,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'10',
                'CTL_CTRLNAMA' =>'SELANGOR DARUL EHSAN',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>3,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'06',
                'CTL_CTRLNAMA' =>'PAHANG DARUL MAKMUR',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>4,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'03',
                'CTL_CTRLNAMA' =>'KELANTAN DARUL NAIM',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'01',
                'CTL_CTRLNAMA' =>'JOHOR DARUL TAKZIM',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'02',
                'CTL_CTRLNAMA' =>'KEDAH DARUL AMAN',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>7,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'15',
                'CTL_CTRLNAMA' =>'WILAYAH PERSEKUTUAN (LABUAN)',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>8,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'04',
                'CTL_CTRLNAMA' =>'MELAKA',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>9,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'05',
                'CTL_CTRLNAMA' =>'NEGERI SEMBILAN DARUL KHUSUS',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>10,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'07',
                'CTL_CTRLNAMA' =>'PULAU PINANG',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>11,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'13',
                'CTL_CTRLNAMA' =>'SARAWAK',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>12,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'09',
                'CTL_CTRLNAMA' =>'PERLIS',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>13,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'12',
                'CTL_CTRLNAMA' =>'SABAH',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>14,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'11',
                'CTL_CTRLNAMA' =>'TERENGGANU DARUL IMAN',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>15,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'16',
                'CTL_CTRLNAMA' =>'WILAYAH PERSEKUTUAN (PUTRAJAYA)',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>16,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'14',
                'CTL_CTRLNAMA' =>'WILAYAH PERSEKUTUAN (KUALA LUMPUR)',
                'CTL_CTRLGRP' =>'NEGERI',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>17,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],

            //added by izzuddin 27/1/2026
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'07',
                'CTL_CTRLNAMA' =>'PBT-PENYEMAK',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'08',
                'CTL_CTRLNAMA' =>'PBT-PPT',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'09',
                'CTL_CTRLNAMA' =>'ATL-PENYEMAK',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'10',
                'CTL_CTRLNAMA' =>'ATL-KETUA-JABATAN',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'11',
                'CTL_CTRLNAMA' =>'BTD-PENYEMAK',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>5,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' =>'12',
                'CTL_CTRLNAMA' =>'BTD-KETUA-JABATAN',
                'CTL_CTRLGRP' =>'PENGGUNA',
                'CTL_CTRLSTATUS' =>'A',
                'CTL_CTRLNOSEQ' =>6,
                'CTL_IUSER' =>null,
                'CTL_UUSER' =>null,
                'CTL_IDATE' =>null,
                'CTL_UDATE' =>null
            ],

            //for master data parameter am input field
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '1',
                'CTL_CTRLNAMA' => 'NAMA MAJLIS',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 1,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '2',
                'CTL_CTRLNAMA' => 'NAMA SINGKATAN MAJLIS',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 2,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '3',
                'CTL_CTRLNAMA' => 'NAMA SISTEM',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 3,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '4',
                'CTL_CTRLNAMA' => 'VERSI SISTEM',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 4,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '5',
                'CTL_CTRLNAMA' => 'FORMAT NO AKAUN LESEN',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 5,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '6',
                'CTL_CTRLNAMA' => 'WARNA TEMA',
                'CTL_CTRLGRP' => 'SYSPARAM',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => 5,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
<<<<<<< HEAD
=======
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '6',
                'CTL_CTRLNAMA' => '6 BULAN',
                'CTL_CTRLGRP' => 'TEMPOH',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => null,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '12',
                'CTL_CTRLNAMA' => '12 BULAN',
                'CTL_CTRLGRP' => 'TEMPOH',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => null,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '24',
                'CTL_CTRLNAMA' => '24 BULAN',
                'CTL_CTRLGRP' => 'TEMPOH',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => null,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
            [
                'CTL_IDPBT' => 'OSCL',
                'CTL_CTRLCODE' => '36',
                'CTL_CTRLNAMA' => '36 BULAN',
                'CTL_CTRLGRP' => 'TEMPOH',
                'CTL_CTRLSTATUS' => 'A',
                'CTL_CTRLNOSEQ' => null,
                'CTL_IUSER' => null,
                'CTL_UUSER' => null,
                'CTL_IDATE' => null,
                'CTL_UDATE' => null
            ],
>>>>>>> upstream/main
        ];

        DB::table('osc_slg_lookuptable')->truncate();
        DB::table('osc_slg_lookuptable')->insert($lookupTables);
    }
}
