<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_slg_menu')->insert([
            [
                'ID' =>1,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Baka Anjing',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>null,
                'MENU_ID' =>301,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'listBakaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>9,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>2,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Tempat Anjing Di Pelihara',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>null,
                'MENU_ID' =>302,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'listTmptPeliharaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>10,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>3,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Senarai Edit Maklumat Penyelenggaraan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>null,
                'MENU_ID' =>303,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'SenaraiEditLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>4,
                'MENU_GROUP_ID' =>'MENU4',
                'MENU_DESC' =>'Bil Tahunan Kelompok',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>null,
                'MENU_ID' =>300,
                'NAME_SPACE' =>'proses',
                'ACTION_LINK' =>'BilTahunanLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>5,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Mukim \/ Kawasan \/ Jalan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>5,
                'MENU_ID' =>165,
                'NAME_SPACE' =>'epbt',
                'ACTION_LINK' =>'FramefindMukimList',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>8,
                'WEB_APPL_TYPE' =>'P',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'KodSistem',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>6,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Jenis Lesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>6,
                'MENU_ID' =>201,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findJenLesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>7,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Mesej  Atas Bil',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPP09',
                'MENU_SEQ' =>4,
                'MENU_ID' =>12,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'inputMesejLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>8,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Perniagaan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPP08',
                'MENU_SEQ' =>3,
                'MENU_ID' =>11,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findNiagaListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>9,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Unit Kawalan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPP07',
                'MENU_SEQ' =>2,
                'MENU_ID' =>10,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findKawalanListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>10,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Undang-undang Kecil',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPP06',
                'MENU_SEQ' =>1,
                'MENU_ID' =>9,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findUndangListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>11,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Sektor\/Kategori',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>7,
                'MENU_ID' =>202,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findSektorKtgriLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>12,
                'MENU_GROUP_ID' =>'MENU1',
                'MENU_DESC' =>'Aktiviti',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>8,
                'MENU_ID' =>203,
                'NAME_SPACE' =>'kod',
                'ACTION_LINK' =>'findAktvtLesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>13,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Fail-Fail Kod',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU1',
                'MENU_SEQ' =>1,
                'MENU_ID' =>1,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU1',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-file-text',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>14,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Permohonan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU2',
                'MENU_SEQ' =>2,
                'MENU_ID' =>2,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU2',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-list-alt',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>15,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Pemprosesan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU4',
                'MENU_SEQ' =>4,
                'MENU_ID' =>3,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU4',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-gears',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>16,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Laporan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU5',
                'MENU_SEQ' =>5,
                'MENU_ID' =>4,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU5',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-file',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>17,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Pertanyaan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU6',
                'MENU_SEQ' =>6,
                'MENU_ID' =>5,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU6',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-info-circle',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>18,
                'MENU_GROUP_ID' =>'MENU2',
                'MENU_DESC' =>'Caj Borang Permohonan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPM00',
                'MENU_SEQ' =>1,
                'MENU_ID' =>154,
                'NAME_SPACE' =>'mohon',
                'ACTION_LINK' =>'listBorangLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>19,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Catatan Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP01',
                'MENU_SEQ' =>1,
                'MENU_ID' =>95,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'CatatanLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>20,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Peribadi Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP02',
                'MENU_SEQ' =>2,
                'MENU_ID' =>96,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'PelesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>21,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Transaksi Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP03',
                'MENU_SEQ' =>3,
                'MENU_ID' =>97,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'TransaksiLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>22,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Iklan Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP04',
                'MENU_SEQ' =>4,
                'MENU_ID' =>98,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'IklanLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>23,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Premis Makanan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP05',
                'MENU_SEQ' =>5,
                'MENU_ID' =>99,
                'NAME_SPACE' =>'selengara',
                'ACTION_LINK' =>'PremisLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>24,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Cetakan Pre-printed',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU51',
                'MENU_SEQ' =>1,
                'MENU_ID' =>101,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU51',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>25,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Kewangan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU52',
                'MENU_SEQ' =>2,
                'MENU_ID' =>102,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU52',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>26,
                'MENU_GROUP_ID' =>'MENU4',
                'MENU_DESC' =>'Penyediaan Bil',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTU01',
                'MENU_SEQ' =>1,
                'MENU_ID' =>22,
                'NAME_SPACE' =>'proses',
                'ACTION_LINK' =>'SediaBilLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>27,
                'MENU_GROUP_ID' =>'MENU4',
                'MENU_DESC' =>'Hujung Penggal',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTU03',
                'MENU_SEQ' =>2,
                'MENU_ID' =>23,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>null,
                'WEB_APPL_TYPE' =>null,
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>28,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Penyata Akaun',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTH01',
                'MENU_SEQ' =>2,
                'MENU_ID' =>107,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'PenyataAkaunLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>29,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Bil Lesen Terkini',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ03',
                'MENU_SEQ' =>3,
                'MENU_ID' =>108,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'BilLesenLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>30,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Hutang Terkini',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ04',
                'MENU_SEQ' =>4,
                'MENU_ID' =>109,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'HutangTerkiniLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>31,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Daftar Permohonan Lesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LPPM07',
                'MENU_SEQ' =>6,
                'MENU_ID' =>162,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'DaftarMohonLesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>32,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Maklumat Induk',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ06',
                'MENU_SEQ' =>6,
                'MENU_ID' =>111,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'IndukLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>33,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Terimaan - Transaksi',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ07',
                'MENU_SEQ' =>7,
                'MENU_ID' =>112,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'TerimaTransLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>34,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Transaksi Lesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ08',
                'MENU_SEQ' =>8,
                'MENU_ID' =>113,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'TransLesenLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>8,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>35,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Maklumat Cagaran \/ Pelit',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ09',
                'MENU_SEQ' =>9,
                'MENU_ID' =>114,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'CagarPelitLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>9,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>36,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Maklumat Iklan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ10',
                'MENU_SEQ' =>10,
                'MENU_ID' =>115,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'IklanLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>10,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>37,
                'MENU_GROUP_ID' =>'MENU51',
                'MENU_DESC' =>'Bil Lesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTP22',
                'MENU_SEQ' =>1,
                'MENU_ID' =>116,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'BilLesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>38,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Penyelenggaraan',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU3',
                'MENU_SEQ' =>3,
                'MENU_ID' =>88,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU3',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-wrench',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>39,
                'MENU_GROUP_ID' =>'MENU51',
                'MENU_DESC' =>'Surat Dan Notis',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTP00',
                'MENU_SEQ' =>8,
                'MENU_ID' =>161,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'SuratNotisLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>40,
                'MENU_GROUP_ID' =>'MENU3',
                'MENU_DESC' =>'Laporan dan Kemaskini Fail',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LCMP06',
                'MENU_SEQ' =>6,
                'MENU_ID' =>100,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>null,
                'WEB_APPL_TYPE' =>null,
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>41,
                'MENU_GROUP_ID' =>'MENU2',
                'MENU_DESC' =>'Kemasukan Maklumat',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPM01',
                'MENU_SEQ' =>2,
                'MENU_ID' =>91,
                'NAME_SPACE' =>'mohon',
                'ACTION_LINK' =>'listPemohonLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>42,
                'MENU_GROUP_ID' =>'MENU2',
                'MENU_DESC' =>'Senarai Permohonan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPM02',
                'MENU_SEQ' =>3,
                'MENU_ID' =>92,
                'NAME_SPACE' =>'mohon',
                'ACTION_LINK' =>'inputPermohonanCetakLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>43,
                'MENU_GROUP_ID' =>'MENU2',
                'MENU_DESC' =>'Kemaskini Maklumat',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPN01',
                'MENU_SEQ' =>4,
                'MENU_ID' =>93,
                'NAME_SPACE' =>'mohon',
                'ACTION_LINK' =>'listKeputusanLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>44,
                'MENU_GROUP_ID' =>'MENU2',
                'MENU_DESC' =>'Surat-Surat',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPM04',
                'MENU_SEQ' =>5,
                'MENU_ID' =>94,
                'NAME_SPACE' =>'mohon',
                'ACTION_LINK' =>'SuratLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>45,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Statistik',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'MENU53',
                'MENU_SEQ' =>3,
                'MENU_ID' =>103,
                'NAME_SPACE' =>null,
                'ACTION_LINK' =>null,
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU53',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>46,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Laporan Pelbagai',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LPPM00',
                'MENU_SEQ' =>4,
                'MENU_ID' =>104,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanPelbagaiLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>47,
                'MENU_GROUP_ID' =>'MENU5',
                'MENU_DESC' =>'Maklumat Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPU00',
                'MENU_SEQ' =>5,
                'MENU_ID' =>105,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'MaklumatPelesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>48,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Hutang Individu',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTQ01',
                'MENU_SEQ' =>1,
                'MENU_ID' =>106,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'HutangIndLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>49,
                'MENU_GROUP_ID' =>'MENU51',
                'MENU_DESC' =>'Penyata Akaun Individu',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTHL05',
                'MENU_SEQ' =>2,
                'MENU_ID' =>117,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'PenAkaunIndvLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>50,
                'MENU_GROUP_ID' =>'MENU51',
                'MENU_DESC' =>'Maklumat Pembayaran',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTP05',
                'MENU_SEQ' =>3,
                'MENU_ID' =>118,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'MakPembayaranLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>51,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Pelesen Berhutang',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML02',
                'MENU_SEQ' =>2,
                'MENU_ID' =>124,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'PelesenBerhutangLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>52,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Tahunan (Kod Perniagaan)',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML03',
                'MENU_SEQ' =>3,
                'MENU_ID' =>125,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'TahunanKodNiagaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>53,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Tahunan (Kod Transaksi)',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML04',
                'MENU_SEQ' =>4,
                'MENU_ID' =>126,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'TahunanTransaksiLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>54,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Kawalan Bil',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML05',
                'MENU_SEQ' =>5,
                'MENU_ID' =>127,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'KawalanBilLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>55,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Resit Tahun Semasa',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML06',
                'MENU_SEQ' =>6,
                'MENU_ID' =>128,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'ResitTahunSemasaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>56,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Senarai Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML07',
                'MENU_SEQ' =>7,
                'MENU_ID' =>129,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'SenPelesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>57,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Tunggakan Pelesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTML08',
                'MENU_SEQ' =>8,
                'MENU_ID' =>130,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'TunggakanPelesenLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>58,
                'MENU_GROUP_ID' =>'MENU52',
                'MENU_DESC' =>'Laporan Tahunan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTHL00',
                'MENU_SEQ' =>9,
                'MENU_ID' =>131,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanTahunanLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>8,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>59,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Kaum - Perniagaan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ01',
                'MENU_SEQ' =>1,
                'MENU_ID' =>135,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'findLaporanKaumNiagaListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>60,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'kaum - Lokasi',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ02',
                'MENU_SEQ' =>2,
                'MENU_ID' =>136,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'findLaporanKaumLokasiListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>61,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Kaum - Pengusaha',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ03',
                'MENU_SEQ' =>3,
                'MENU_ID' =>137,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'findLaporanKaumPengusahaListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>62,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Kaum - Papan Iklan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ04',
                'MENU_SEQ' =>4,
                'MENU_ID' =>138,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'findLaporanKaumIklanListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>63,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Kaum - Kawasan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ05',
                'MENU_SEQ' =>5,
                'MENU_ID' =>139,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'findLaporanKaumKawasanListLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>64,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Laporan Statistik Ikut Kaum',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTMQ06',
                'MENU_SEQ' =>6,
                'MENU_ID' =>140,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanStatKaumLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>65,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Laporan Statistik Kawasan & Kod Niaga',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LPPM04',
                'MENU_SEQ' =>7,
                'MENU_ID' =>141,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanStatKawNiagaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>66,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Laporan Statistik Pelesen & Lokasi',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LPPM05',
                'MENU_SEQ' =>8,
                'MENU_ID' =>142,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanStatLesenLokLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>8,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>67,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Laporan Statistik Kod Niaga & Lokasi',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LPPM06',
                'MENU_SEQ' =>9,
                'MENU_ID' =>143,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanStatNLokasLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>9,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>68,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Laporan Statistik Kaum\/Lokasi\/Kod Niaga',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LRACLP',
                'MENU_SEQ' =>10,
                'MENU_ID' =>144,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'LaporanStatKaumLokasiNLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>10,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>69,
                'MENU_GROUP_ID' =>'MENU53',
                'MENU_DESC' =>'Statistik Kod Perniagaan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LEPR09',
                'MENU_SEQ' =>11,
                'MENU_ID' =>145,
                'NAME_SPACE' =>'laporan',
                'ACTION_LINK' =>'StatKodNiagaLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>11,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>70,
                'MENU_GROUP_ID' =>'MENU4',
                'MENU_DESC' =>'Reset Penyediaan Bil',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'LTTU04',
                'MENU_SEQ' =>3,
                'MENU_ID' =>163,
                'NAME_SPACE' =>'proses',
                'ACTION_LINK' =>'ResetBilLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>71,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Transaksi Lesen',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>994,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'TransLesenLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>5,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>72,
                'MENU_GROUP_ID' =>'MENU0',
                'MENU_DESC' =>'Carian Akaun',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'n',
                'MENU_SEQ' =>null,
                'MENU_ID' =>164,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'carianAkaunLink2',
                'WEB_CONTROL' =>'Y',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'S',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>'fa fa-search',
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>73,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Maklumat Cagaran \/ Pelit',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>993,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'CagarPelitLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>6,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>74,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Hutang Individu',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>996,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'HutangIndLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>3,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>75,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Maklumat Iklan',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>992,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'IklanLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>7,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>76,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Penyata Akaun',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>997,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'PenyataAkaunLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>2,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>77,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Bil Lesen Terkini',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>995,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'BilLesenLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>4,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>78,
                'MENU_GROUP_ID' =>'MENU6',
                'MENU_DESC' =>'Maklumat Induk (NEW)',
                'MENU_APPL_TYPE' =>'M',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>998,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'IndukLink2',
                'WEB_CONTROL' =>'N',
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'M',
                'WEB_MENU_CALL' =>'MENU61',
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ],
            [
                'ID' =>79,
                'MENU_GROUP_ID' =>'MENU61',
                'MENU_DESC' =>'Maklumat Induk',
                'MENU_APPL_TYPE' =>'F',
                'MENU_CALL' =>'a',
                'MENU_SEQ' =>null,
                'MENU_ID' =>999,
                'NAME_SPACE' =>'tanya',
                'ACTION_LINK' =>'IndukLink2',
                'WEB_CONTROL' =>null,
                'WEB_SEQ' =>1,
                'WEB_APPL_TYPE' =>'F',
                'WEB_MENU_CALL' =>null,
                'PROJECT_NAME' =>null,
                'MENU_ICON' =>null,
                'WEB_TAB' =>null,
                'WEB_IUSER' =>null,
                'WEB_UUSER' =>null
            ]

        ]);
    }
}
