<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodAktivitiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_aktiviti')->insert(
        [
            [
                'ID' => 1,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0003',
                'TVT_TVTNAMA' => 'KEDAI AKSESORI WANITA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 2,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0004',
                'TVT_TVTNAMA' => 'KEDAI AKUARIUM',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 3,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0005',
                'TVT_TVTNAMA' => 'KEDAI ALAT-ALAT \/ KELENGKAPAN MUZIK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 4,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0006',
                'TVT_TVTNAMA' => 'KEDAI ALAT-ALAT SUKAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 5,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0007',
                'TVT_TVTNAMA' => 'KEDAI ANDAMAN DAN PAKAIAN PENGANTIN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 6,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0008',
                'TVT_TVTNAMA' => 'KEDAI BARANG HIASAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 7,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0009',
                'TVT_TVTNAMA' => 'KEDAI BARANG KEMAS DAN PERMATA \/ BERLIAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 8,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0010',
                'TVT_TVTNAMA' => 'KEDAI BARANGAN KEPERLUAN BAYI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 9,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0011',
                'TVT_TVTNAMA' => 'KEDAI BARANGAN PLASTIK DAN PINGGAN MANGKUK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 10,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0012',
                'TVT_TVTNAMA' => 'KEDAI BARANG-BARANG RUNCIT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 11,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0013',
                'TVT_TVTNAMA' => 'KEDAI BEG',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 12,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0014',
                'TVT_TVTNAMA' => 'KEDAI BINANTANG PELIHARAAN \/ KESAYANGAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 13,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0015',
                'TVT_TVTNAMA' => 'KEDAI BINGKAI GAMBAR',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 14,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0016',
                'TVT_TVTNAMA' => 'KEDAI BOT \/ JET SKI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 15,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0017',
                'TVT_TVTNAMA' => 'KEDAI BUAH-BUAHAN \/ SAYURAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 16,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0018',
                'TVT_TVTNAMA' => 'KEDAI BUKU DAN ALAT TULIS',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 17,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0019',
                'TVT_TVTNAMA' => 'KEDAI BUNGA-BUNGAAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 18,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0020',
                'TVT_TVTNAMA' => 'BUTIK \/ PAKAIAN FESYEN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 19,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0021',
                'TVT_TVTNAMA' => 'KEDAI CERMIN MATA (OPTIK)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 20,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0022',
                'TVT_TVTNAMA' => 'KEDAI FOTOSTAT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 21,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0023',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL JAM',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 22,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0024',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL KELENGKAPAN RUMAH DAN PERALATAN RUMAH \/ DAPUR',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 23,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0025',
                'TVT_TVTNAMA' => 'KEDAI KASUT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 24,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0026',
                'TVT_TVTNAMA' => 'KEDAI KRAFTANGAN \/ CENDERAMATA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 25,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0027',
                'TVT_TVTNAMA' => 'KEDAI MEMBUAT KUNCI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 26,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0028',
                'TVT_TVTNAMA' => 'KEDAI MAINAN KANAK-KANAK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 27,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0029',
                'TVT_TVTNAMA' => 'KEDAI PERABOT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 28,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0030',
                'TVT_TVTNAMA' => 'KEDAI PERALATAN KEAGAMAAN \/ ALAT SEMBAHYANG',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 29,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0031',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL BARANGAN KESIHATAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 30,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0032',
                'TVT_TVTNAMA' => 'KEDAI PERALATAN MAKMAL \/ SAINTIFIK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 31,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0033',
                'TVT_TVTNAMA' => 'KEDAI PERHIASAN LAMPU',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 32,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0034',
                'TVT_TVTNAMA' => 'KEDAI PERMAIDANI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 33,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0035',
                'TVT_TVTNAMA' => 'KEDAI PRODUK KESIHATAN \/ MAKANAN KESIHATAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 34,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0036',
                'TVT_TVTNAMA' => 'KEDAI ROTI \/ KEK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 35,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0037',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL TAYAR DAN BATERI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 36,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0038',
                'TVT_TVTNAMA' => 'KEDAI UBAT \/ FARMASI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 37,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0039',
                'TVT_TVTNAMA' => 'KEDAI ALUMINIUM \/ KACA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 38,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0040',
                'TVT_TVTNAMA' => 'KEDAI BASIKAL',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 39,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0041',
                'TVT_TVTNAMA' => 'KEDAI JUAL BELI GETAH',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 40,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0042',
                'TVT_TVTNAMA' => 'KEDAI SERBAGUNA \/ SERBANEKA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 41,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0043',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL KERANDA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 42,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0044',
                'TVT_TVTNAMA' => 'KEDAI HARDWARE',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 43,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0045',
                'TVT_TVTNAMA' => 'MENJUAL HASIL TEMBAKAU',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 44,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0046',
                'TVT_TVTNAMA' => 'MENJUAL MAKANAN TERNAKAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 45,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0047',
                'TVT_TVTNAMA' => 'MENJUAL HASIL LAUT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 46,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0048',
                'TVT_TVTNAMA' => 'MENJUAL MAKANAN \/ MINUMAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 47,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0049',
                'TVT_TVTNAMA' => 'MENJUAL MINUMAN KERAS \/ MINUMAN MEMABUKAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 48,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0050',
                'TVT_TVTNAMA' => 'JUAL ARANG KAYU \/ ARANG BATU',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 49,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0051',
                'TVT_TVTNAMA' => 'MENJUAL MINYAK WANGI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 50,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0052',
                'TVT_TVTNAMA' => 'MENJUAL PRODUK KECANTIKAN (KOSMETIK) \/ PERALATAN KOSMESTIK \/ PERSOLEKAN \/PENJAGAAN DIRI',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 51,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0053',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL ALAT PENDINGIN UDARA \/ PETI SEJUK',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 52,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0054',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL ALAT-ALAT PEMADAM API',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 53,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0055',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL BAJA \/ RACUN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 54,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0056',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL SENJATA API DAN PELURU',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 55,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0057',
                'TVT_TVTNAMA' => 'KEDAI ALATGANTI DAN PERKAKAS KENDERAAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 56,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0058',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL KENDERAAN (MOTOSIKAL\/KERETA\/LORI\/BAS DLL)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 57,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0059',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL BARANG TERPAKAI (PERABOT\/KERETA\/KELENGKAPAN RUMAH\/DLL)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 58,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0060',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL \/ BELI BARANG LUSUH',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 59,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0061',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL PAKAIAN TERPKAI (BUNDLE)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 60,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0062',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL ALAT-ALAT PERUBATAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 61,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0063',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL BARANG-BARANG PERHIASAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 62,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0064',
                'TVT_TVTNAMA' => 'KEDAI GAMBAR\/ MENJUAL ALAT KAMERA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 63,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0065',
                'TVT_TVTNAMA' => 'KEDAI KAIN DAN PAKAIAN',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 64,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0066',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL PERABOT DAN ALATAN PEJABAT',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 65,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0067',
                'TVT_TVTNAMA' => 'MENJUAL BARANGAN \/ ALAT ELEKTRONIK \/ KAMUS ELEKTRONIK (TERMASUK ALAT GANTI DAN AKSESORI)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 66,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0068',
                'TVT_TVTNAMA' => 'MENJUAL KOMPUTER \/ (TERMASUK AKSESORI KOMPUTER)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 67,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0069',
                'TVT_TVTNAMA' => 'MENJUAL & MENYEWA CD, VCD, DVD & VIDEO TAPE',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 68,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0070',
                'TVT_TVTNAMA' => 'MENJUAL PERMAINAN VIDEO (TERMASUK AKSESORI)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 69,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0071',
                'TVT_TVTNAMA' => 'MENJUAL PERALATAN TELEKOMUNIKASI \/ TELEFON BIMBIT DAN AKSESORI (TERMASUK KAD PRABAYAR)',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 70,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0002',
                'TVT_TVTNAMA' => 'AGENSI HARTANAH',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 71,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0003',
                'TVT_TVTNAMA' => 'AGENSI KHIDMAT KAWAL KESELAMATAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 72,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0004',
                'TVT_TVTNAMA' => 'AGENSI PELELONG',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 73,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0005',
                'TVT_TVTNAMA' => 'SYARIKAT PEMAJU PERUMAHAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 74,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0006',
                'TVT_TVTNAMA' => 'KONTRAKTOR',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 75,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0007',
                'TVT_TVTNAMA' => 'AGENSI PEKERJAAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 76,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0008',
                'TVT_TVTNAMA' => 'SYARIKAT PENGANGKUTAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 77,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0009',
                'TVT_TVTNAMA' => 'SYARIKAT PERUNDINGAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 78,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0010',
                'TVT_TVTNAMA' => 'SEMUA JENIS-JENIS PERNIAGAAN, AGEN PERNIAGAAN KEPERLUAN RUMAH, AGEN PELANCONGAN ATAU AGEN KAWALAN KESELAMATAN ATAU LAIN-LAIN AGEN YANG TIDAK TERSENARAI',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 79,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0011',
                'TVT_TVTNAMA' => 'LAIN-LAIN AKTIVITI PERNIAGAAN \/ KOMERSIL',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 80,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0001',
                'TVT_TVTNAMA' => 'BAHAN MENTAH (DAGING \/ IKAN \/ AYAM)',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 81,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0002',
                'TVT_TVTNAMA' => 'BUAH-BUAHAN \/ SAYURAN',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 82,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'A0001',
                'TVT_TVTNAMA' => 'KILANG MEMBUAT ALAT TULIS',
                'TVT_KODSEKTOR' => '10001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 83,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'A0002',
                'TVT_TVTNAMA' => 'KILANG MEMBUAT BARANG KIMIA (INDUSTRI DAN PERTANIAN)',
                'TVT_KODSEKTOR' => '10001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 84,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'B0001',
                'TVT_TVTNAMA' => 'KEDAI AKSESORI KERETA',
                'TVT_KODSEKTOR' => '10002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 85,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'C0001',
                'TVT_TVTNAMA' => 'AGENSI PELANCONGAN',
                'TVT_KODSEKTOR' => '10003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 86,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'D0001',
                'TVT_TVTNAMA' => 'SEKOLAH SWASTA \/ SEKOLAH ANTARABANGSA',
                'TVT_KODSEKTOR' => '10004',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 87,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0023',
                'TVT_TVTNAMA' => 'PUSAT SERVIS KENDERAAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 88,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0001',
                'TVT_TVTNAMA' => 'DEWAN MUZIK',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 89,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0002',
                'TVT_TVTNAMA' => 'KARAOKE',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 90,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0003',
                'TVT_TVTNAMA' => 'PANGGUNG WAYANG',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 91,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0004',
                'TVT_TVTNAMA' => 'PUSAT HIBURAN KELUARGA \/ TAMAN TEMA',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 92,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0005',
                'TVT_TVTNAMA' => 'PUSAT PERMAINAN VIDEO',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 93,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0006',
                'TVT_TVTNAMA' => 'PUSAT SIBER \/ KAFE SIBER',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 94,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0007',
                'TVT_TVTNAMA' => 'PUSAT SNOOKER \/ BILLIARD \/ AMERICAN POOL TABLE',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 95,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0008',
                'TVT_TVTNAMA' => 'PUB \/ BAR \/ LOUNGE',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 96,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0009',
                'TVT_TVTNAMA' => 'DISKO',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 97,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0010',
                'TVT_TVTNAMA' => 'RUMAH AIR',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 98,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0011',
                'TVT_TVTNAMA' => 'PAINTBALL',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 99,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0012',
                'TVT_TVTNAMA' => 'BOWLING',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 100,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0013',
                'TVT_TVTNAMA' => 'AKTIVITI PERTARUHAN \/ AGENSI NOMBOR RAMALAN \/ TIKET TOTO',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 101,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'K0014',
                'TVT_TVTNAMA' => 'MESIN DART ELEKTRONIK',
                'TVT_KODSEKTOR' => '10011',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 102,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0002',
                'TVT_TVTNAMA' => 'BUNGA-BUNGAAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 103,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0024',
                'TVT_TVTNAMA' => 'STESEN MINYAK',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 104,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0025',
                'TVT_TVTNAMA' => 'HYPERMARKET \/ SUPERMARKET',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 105,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0026',
                'TVT_TVTNAMA' => 'KEDAI MEMBAIKI \/ MENGECAJ BATERI',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 106,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0027',
                'TVT_TVTNAMA' => 'PUSAT SUKAN (BADMINTON \/FUTSAL \/ AEROBIK\/ GIMNASIUM\/ KASUT RODA DLL)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 107,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0028',
                'TVT_TVTNAMA' => 'PUSAT PAMERAN (KENDERAAN \/ PERALATAN RUMAH \/ PERALATAN INDUSTRI DLL)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 108,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0029',
                'TVT_TVTNAMA' => 'PUSAT SEMBELIHAN BINATANG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 109,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0022',
                'TVT_TVTNAMA' => 'MEMBAIKI BASIKAL',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 110,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0003',
                'TVT_TVTNAMA' => 'MAKANAN BERMASAK',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 111,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0004',
                'TVT_TVTNAMA' => 'PRODUK MAKANAN',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 112,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0005',
                'TVT_TVTNAMA' => 'MINUMAN',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 113,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0006',
                'TVT_TVTNAMA' => 'PRODUK KESIHATAN',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 114,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'L0007',
                'TVT_TVTNAMA' => 'LAIN-LAIN (BERKAITAN PRODUK MAKANAN \/ MINUMAN)',
                'TVT_KODSEKTOR' => '20001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 115,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0001',
                'TVT_TVTNAMA' => 'BUKU DAN ALAT TULIS',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 116,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0003',
                'TVT_TVTNAMA' => 'PAKAIAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 117,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0004',
                'TVT_TVTNAMA' => 'CERMIN MATA',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 118,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0005',
                'TVT_TVTNAMA' => 'FOTOGRAFI',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 119,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0006',
                'TVT_TVTNAMA' => 'JAM',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 120,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0007',
                'TVT_TVTNAMA' => 'KELENGKAPAN RUMAH DAN PERALATAN RUMAH \/ DAPUR',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 121,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0008',
                'TVT_TVTNAMA' => 'KASET, PITA VIDEO \/ REKOD',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 122,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0009',
                'TVT_TVTNAMA' => 'KASUT',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 123,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0010',
                'TVT_TVTNAMA' => 'KRAFTANGAN \/ CENDERAMATA',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 124,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0011',
                'TVT_TVTNAMA' => 'MAINAN KANAK-KANAK ',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 125,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0012',
                'TVT_TVTNAMA' => 'PERALATAN KEAGAMAAN ',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 126,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0013',
                'TVT_TVTNAMA' => 'BARANGAN KESIHATAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 127,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0014',
                'TVT_TVTNAMA' => 'PERHIASAN LAMPU',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 128,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0015',
                'TVT_TVTNAMA' => 'PERMAIDANI',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 129,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0016',
                'TVT_TVTNAMA' => 'UBAT-UBATAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 130,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0017',
                'TVT_TVTNAMA' => 'RACUN SERANGGA',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 131,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0018',
                'TVT_TVTNAMA' => 'SERBAGUNA \/ SERBENEKA',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 132,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0019',
                'TVT_TVTNAMA' => 'HARDWARE\/ LOGAM',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 133,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0020',
                'TVT_TVTNAMA' => 'BARANG KOSMETIK \/ TOILETRIES',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 134,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0021',
                'TVT_TVTNAMA' => 'AKSESORI KENDERAAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 135,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0022',
                'TVT_TVTNAMA' => 'AKSESORI WANITA \/ LELAKI',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 136,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0023',
                'TVT_TVTNAMA' => 'ALAT-ALAT \/ KELENGKAPAN MUZIK',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 137,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0024',
                'TVT_TVTNAMA' => 'ALAT-ALAT SUKAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 138,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0025',
                'TVT_TVTNAMA' => 'BARANG HIASAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 139,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0026',
                'TVT_TVTNAMA' => 'BARANG KEMAS DAN PERMATA',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 140,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0027',
                'TVT_TVTNAMA' => 'BARANGAN ELEKTRIK',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 141,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0028',
                'TVT_TVTNAMA' => 'BARANGAN KEPERLUAN BAYI',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 142,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0029',
                'TVT_TVTNAMA' => 'BARANGAN PLASTIK DAN PINGGAN MANGKUK',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 143,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0030',
                'TVT_TVTNAMA' => 'BARANG-BARANG RUNCIT',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 144,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0031',
                'TVT_TVTNAMA' => 'BEG',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 145,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0032',
                'TVT_TVTNAMA' => 'BINATANG PELIHARAAN',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 146,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'M0033',
                'TVT_TVTNAMA' => 'LAIN-LAIN (BERKAITAN PRODUK BUKAN MAKANAN)',
                'TVT_KODSEKTOR' => '20002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 147,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0001',
                'TVT_TVTNAMA' => 'BEKAM \/ REFLEKSOLOGI\/ TABIB\/ AKUPUNTUR\/ URUTAN TRADISIONAL',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 148,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0002',
                'TVT_TVTNAMA' => 'LAIN-LAIN RAWATAN TRADISIONAL',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 149,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0003',
                'TVT_TVTNAMA' => 'MENJAHIT PAKAIAN',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 150,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0004',
                'TVT_TVTNAMA' => 'MEMBAIKI KASUT',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 151,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0005',
                'TVT_TVTNAMA' => 'MEMBUAT KUNCI DAN BERKAITAN',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 152,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0006',
                'TVT_TVTNAMA' => 'GUNTING RAMBUNG',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 153,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0007',
                'TVT_TVTNAMA' => 'PROMOSI\/ SEWAAN PERALATAN PERMAINAN (ROLLER BLADE\/ BELON KANAK-KANAK DLL)',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 154,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'N0008',
                'TVT_TVTNAMA' => 'LAIN-LAIN PERKHIDMATAN',
                'TVT_KODSEKTOR' => '20003',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 155,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0001',
                'TVT_TVTNAMA' => 'KHIDMAT PERCETAKAN ',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 156,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0002',
                'TVT_TVTNAMA' => 'PENGIKLANAN (PAPAN TANDA \/ BANNER DLL)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 157,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0003',
                'TVT_TVTNAMA' => 'KEDAI PEMBUAT KUSYEN \/ PERMAIDANI \/ JAHIT MENJAHIT \/ HIASAN RUMAH, BUNGA - BUNGA PLASTIK',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 158,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0004',
                'TVT_TVTNAMA' => 'PUSAT RAKAMAN VIDEO \/ STUDIO MUZIK',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 159,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0005',
                'TVT_TVTNAMA' => 'MEMBAIKI PERALATAN ELEKTRIK KEGUNAAN RUMAH \/ KOMERSIAL',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 160,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0006',
                'TVT_TVTNAMA' => 'KEDDAI MENYEWAKAN ALATAN \/ PERABOT RUMAH \/ KELENGKAPAN PEJABAT',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 161,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0007',
                'TVT_TVTNAMA' => 'PUSAT MENCUCI KENDERAAN \/ JAGAAN KENDERAAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 162,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0008',
                'TVT_TVTNAMA' => 'DOBI DAN CUCI KERING (TERMASUK LAYAN DIRI)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 163,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0009',
                'TVT_TVTNAMA' => 'PERKHIDMATAN PENGHANTARAN CEAPT \/ COURIER',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 164,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0010',
                'TVT_TVTNAMA' => 'KEDAI MENJUAL \/ MEMBAIKI \/ PERKHIDMATAN KALIBRASI ALAT TIMBANG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 165,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0011',
                'TVT_TVTNAMA' => 'KEDAI MEMBAIKI KASUT',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 166,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0012',
                'TVT_TVTNAMA' => 'KEDAI MENJAHIT PAKAIAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 167,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0013',
                'TVT_TVTNAMA' => 'KEDAI PENJILID BUKU',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 168,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0014',
                'TVT_TVTNAMA' => 'KEDAI PAJAK GADAI',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 169,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0015',
                'TVT_TVTNAMA' => 'PEMBERI PINJAM WANG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 170,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0016',
                'TVT_TVTNAMA' => 'SALON KECANTIKAN \/ GUNTING RAMBUT',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 171,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0017',
                'TVT_TVTNAMA' => 'PERKHIDMATAN TELEFON PANGGILAN JAUH \/ VIDEO',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 172,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0018',
                'TVT_TVTNAMA' => 'PUSAT PERKHIDMATANTELEFON BIMBIT (SERVICE CENTER - MAXIS, DIGI, CELCOM, DLL)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 173,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0019',
                'TVT_TVTNAMA' => 'MEMBAIKI TELEFON BIMBIT DAN AKSESORI',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 174,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0020',
                'TVT_TVTNAMA' => 'SERVIS KOMPUTER \/ (TERMASUK AKSESORI KOMPUTER)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 175,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0021',
                'TVT_TVTNAMA' => 'PUSAT KECANTIKAN, PERSOLEKAN, KECANTIKAN KUKU DAN KAKI',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 176,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0001',
                'TVT_TVTNAMA' => 'BAHAN MENTAH (DAGING \/ IKAN \/ AYAM)',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 177,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0002',
                'TVT_TVTNAMA' => 'BUAH - BUAHAN \/ SAYURAN',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 178,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0003',
                'TVT_TVTNAMA' => 'MAKANAN BERMASAK',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 179,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0004',
                'TVT_TVTNAMA' => 'PRODUK MAKANAN',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 180,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0005',
                'TVT_TVTNAMA' => 'MINUMAN',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 181,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0006',
                'TVT_TVTNAMA' => 'PRODUK KESIHATAN',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 182,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'P0007',
                'TVT_TVTNAMA' => 'LAIN - LAIN',
                'TVT_KODSEKTOR' => '30001',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 183,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'Q0001',
                'TVT_TVTNAMA' => 'BUKU DAN ALAT TULIS',
                'TVT_KODSEKTOR' => '30002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 184,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0030',
                'TVT_TVTNAMA' => 'KEDAI MENGISAR REMPAH \/ TEPUNG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 185,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0031',
                'TVT_TVTNAMA' => 'PENGURUSAN MAKANAN (KATERING)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 186,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0032',
                'TVT_TVTNAMA' => 'RESTORAN \/ PREMIS MAKANAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 187,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0033',
                'TVT_TVTNAMA' => 'KANTIN SEKOLAH \/ PEJABAT \/ KILANG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 188,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0034',
                'TVT_TVTNAMA' => 'TEMPAT LETAK KERETA',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 189,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0035',
                'TVT_TVTNAMA' => 'RUMAH ASAP',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 190,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0036',
                'TVT_TVTNAMA' => 'MEMANCING IKAN \/ UDANG',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 191,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0037',
                'TVT_TVTNAMA' => 'TAPAK SEMAIAN NURSERY',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 192,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0038',
                'TVT_TVTNAMA' => 'TERNAKAN BINATANG (LEMBU \/ KERBAU \/ KUDA DLL)',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 193,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0039',
                'TVT_TVTNAMA' => 'PERUSAHAAN SARANG BURUNG WALIT',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 194,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0040',
                'TVT_TVTNAMA' => 'TANAMAN PERTANIAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 195,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0041',
                'TVT_TVTNAMA' => 'TERNAKAN BELUT \/ UDANG \/ IKAN \/ LINTAH',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 196,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0042',
                'TVT_TVTNAMA' => 'DEWAN KONVOKESYEN \/ SEMINAR',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 197,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'J0043',
                'TVT_TVTNAMA' => 'LAIN - LAIN AKTIVITI MEMBERI PERKHIDMATAN',
                'TVT_KODSEKTOR' => '10010',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 198,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'Q0002',
                'TVT_TVTNAMA' => 'BUNGA - BUNGAAN',
                'TVT_KODSEKTOR' => '30002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 199,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'Q0003',
                'TVT_TVTNAMA' => 'PAKAIAN FESYEN',
                'TVT_KODSEKTOR' => '30002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ],
            [
                'ID' => 200,
                'TVT_IDPBT' => 'PRK_MDTM',
                'TVT_KODAKTIVITI' => 'Q0004',
                'TVT_TVTNAMA' => 'CERMIN MATA',
                'TVT_KODSEKTOR' => '30002',
                'TVT_IDATE' => '2025-12-19',
                'TVT_UDATE' => null,
                'TVT_IUSER' => 'CSM_ZUBAIRI',
                'TVT_UUSER' => null
            ]
        ]);
    }
}
