<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodUndangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_undang')->insert([
            [
                'id' => 1,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '05',
                'und_ketrng1' => 'UUK PELESENAN TRED PERNIAGAAN DAN PERINDUSTRIAN (MDTM) 2017',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 2,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '2',
                'und_ketrng1' => 'TIADA SEORANG PUN BOLEH MENGGUNAKAN SESUATU TEMPAT @ PREMIS',
                'und_ketrng2' => 'TANPA LESEN YANG DIKELUARKAN OLEH MAJLIS',
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 3,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '3',
                'und_ketrng1' => '(1)TIAP-TIAP PERMOHONAN UNTUK MENDAPATKAN LESEN HENDAKLAH',
                'und_ketrng2' => 'DIBUAT SECARA BERTULIS KPD YANG DIPERTUA DALAM BORANG YANG',
                'und_ketrng3' => 'DITETAPKAN OLEH YANG DIPERTUA',
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 4,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '3a',
                'und_ketrng1' => '(2)YANG DIPERTUA BOLEH MENGHENDAKI MANA-MANA PEMOHON UNTUK',
                'und_ketrng2' => 'PENGELUARAN @ PEMBAHARUAN LESEN SUPAYA HADIR SENDIRI @ WAKIL',
                'und_ketrng3' => 'YANG DIBERI KUASA SUPAYA HADIR SEMASA LESEN DIKELUARKAN',
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 5,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '4',
                'und_ketrng1' => 'TIAP TIAP LESEN YANG DIKELUARKAN DIBAWAH UNDANG UNDANG KECIL',
                'und_ketrng2' => 'INI HENDAKLAH DALAM BENTUK YANG DITETAPKAN OLEH YANG',
                'und_ketrng3' => 'DIPERTUA DARI MASA KE SEMASA',
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 6,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '01',
                'und_ketrng1' => 'UUK PENJAJA ( MDTM ) 1984',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 7,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '02',
                'und_ketrng1' => 'UUK PELESENAN TRED PERNIAGAAN DAN PERINDUSTRIAN (MDTM) 2017',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 8,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '03',
                'und_ketrng1' => 'UUK IKLAN ( MDTM ) 2015',
                'und_ketrng2' => 'UUK IKLAN ( MDTM ) 1984 (DIBATALKAN)',
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 9,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '04',
                'und_ketrng1' => 'UUK PENGENDALI MAKANAN ( MDTM ) 1983',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 10,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '06',
                'und_ketrng1' => 'UNDANG-UNDANG KECIL PELESENAN ANJING (MDTM) 2005',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 11,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '07',
                'und_ketrng1' => 'UNDANG-UNDANG KECIL KECIL KERAJAAN TEMPATAN',
                'und_ketrng2' => '(IKLAN PILIHANRAYA) MDTM 1990',
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 12,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '13',
                'und_ketrng1' => 'UNDANG-UNDANG KECIL PASAR (MDTM) 2007',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 13,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '14',
                'und_ketrng1' => 'ENAKMEN HOTEL PERAK 2023',
                'und_ketrng2' => 'PERATURAN PERATURAN HOTEL PERAK 2024',
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
            [
                'id' => 14,
                'und_idpbt' => 'PRK_MDTM',
                'und_kodundang' => '08',
                'und_ketrng1' => 'ARAHAN PENTADBIRAN & PEKELILING MDTM',
                'und_ketrng2' => null,
                'und_ketrng3' => null,
                'und_statf' => 'Y',
                'und_idate' => '2025-12-19 00:00:00',
                'und_udate' => null,
                'und_iuser' => 'CSM-ZUBAIRI',
                'und_uuser' => null,
            ],
        ]);
    }
}
