<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodSektorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_sektor')->insert([
            [
                'id' => 1,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10001',
                'skt_sktrnama' => 'PERKILANGAN / PERINDUSTRIAN / BENGKEL / KEJURUTERAAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 2,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10002',
                'skt_sktrnama' => 'PERKHIDMATAN / PERUNCITAN / JUALAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 3,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10003',
                'skt_sktrnama' => 'PERHIDMATAN - PEJABAT URUSAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 4,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10004',
                'skt_sktrnama' => 'PERKHIDMATAN - PUSAT LATIHAN & PENDIDIKAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 5,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10005',
                'skt_sktrnama' => 'PERKHIDMATAN - HOSPITALITI & PERHOTELAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 6,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10006',
                'skt_sktrnama' => 'PERKHIDMATAN - KESIHATAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 7,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10007',
                'skt_sktrnama' => 'PERKHIDMATAN - PENGGUDANGAN & PENYIMPANAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 8,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10008',
                'skt_sktrnama' => 'PERKHIDMATAN - AKTIVITI KEWANGAN DAN INSURAN / TAKAFUL',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 9,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10009',
                'skt_sktrnama' => 'PERKHIDMATAN - PEMBORONG / PEMBEKAL / PENGEDAR',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 10,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10010',
                'skt_sktrnama' => 'AKTIVITI PERKHIDMATAN LAIN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 11,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '10011',
                'skt_sktrnama' => 'AKTIVITI HIBURAN',
                'skt_kodjenis' => '10',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 12,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '30001',
                'skt_sktrnama' => 'MAKANAN/MINUMAN',
                'skt_kodjenis' => '30',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 13,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '20001',
                'skt_sktrnama' => 'MAKANAN / MINUMAN',
                'skt_kodjenis' => '20',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 14,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '20002',
                'skt_sktrnama' => 'BUKAN MAKANAN / PRODUK',
                'skt_kodjenis' => '20',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 15,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '20003',
                'skt_sktrnama' => 'PERKHIDMATAN',
                'skt_kodjenis' => '20',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 16,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '30002',
                'skt_sktrnama' => 'BUKAN MAKANAN / BARANGAN KERING',
                'skt_kodjenis' => '30',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 17,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '30003',
                'skt_sktrnama' => 'HIBURAN',
                'skt_kodjenis' => '30',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 18,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '30004',
                'skt_sktrnama' => 'PERKHIDMATAN',
                'skt_kodjenis' => '30',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 19,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '7',
                'skt_sktrnama' => 'PST',
                'skt_kodjenis' => '71',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 20,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '98',
                'skt_sktrnama' => 'PST',
                'skt_kodjenis' => '98',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 21,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '88',
                'skt_sktrnama' => 'STP',
                'skt_kodjenis' => '88',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
            [
                'id' => 22,
                'skt_idpbt' => 'PRK_MDTM',
                'skt_kodsektor' => '92',
                'skt_sktrnama' => 'PST PTT',
                'skt_kodjenis' => '92',
                'skt_statf' => 'Y',
                'skt_idate' => '2025-12-19 00:00:00',
                'skt_udate' => null,
                'skt_iuser' => 'zubairi',
                'skt_uuser' => null,
            ],
        ]);
    }
}
