<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodAgensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_agensi')->truncate();
        DB::table('osc_kod_agensi')->insert([
            [
                'id' => 1,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JKKP',
                'agn_namaagensi' => 'JABATAN KESELAMATAN DAN KESIHATAN PEKERJAAN',
                'agn_namargks' => 'JKKP',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 2,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JPBM',
                'agn_namaagensi' => 'JABATAN BOMBA DAN PENYELAMAT MALAYSIA',
                'agn_namargks' => 'BOMBA',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 3,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JKR',
                'agn_namaagensi' => 'JABATAN KERJA RAYA',
                'agn_namargks' => 'JKR',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 4,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JPS',
                'agn_namaagensi' => 'JABATAN PENGAIRAN DAN SALIRAN',
                'agn_namargks' => 'JPS',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 5,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'TNB',
                'agn_namaagensi' => 'TENAGA NASIONAL BERHAD',
                'agn_namargks' => 'TNB',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 6,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'IWK',
                'agn_namaagensi' => 'INDAH WATER KONSORTIUM',
                'agn_namargks' => 'IWK',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 7,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'SKMM',
                'agn_namaagensi' => 'SURUHANJAYA KOMUNIKASI DAN MULTIMEDIA MALAYSIA',
                'agn_namargks' => 'SKMM',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 8,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JAS',
                'agn_namaagensi' => 'JABATAN ALAM SEKITAR',
                'agn_namargks' => 'JAS',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 9,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'PTG',
                'agn_namaagensi' => 'PEJABAT TANAH DAN GALIAN',
                'agn_namargks' => 'PTG',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 10,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'PDRM',
                'agn_namaagensi' => 'POLIS DIRAJA MALAYSIA',
                'agn_namargks' => 'PDRM',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 11,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JPV',
                'agn_namaagensi' => 'JABATAN PERKHIDMATAN VETERINAR',
                'agn_namargks' => 'JPV',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 12,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'KDN',
                'agn_namaagensi' => 'KEMENTERIAN DALAM NEGERI',
                'agn_namargks' => 'KDN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 13,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JPN',
                'agn_namaagensi' => 'JABATAN PENDIDIKAN NEGERI',
                'agn_namargks' => 'JPN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 14,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'KPDNHEP',
                'agn_namaagensi' => 'KEMENTERIAN PERDAGANGAN DALAM NEGERI DAN HAL EHWAL PENGGUNA',
                'agn_namargks' => 'KPDNHEP',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 15,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'ST',
                'agn_namaagensi' => 'SURUHANJAYA TENAGA',
                'agn_namargks' => 'ST',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 16,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'BPLN',
                'agn_namaagensi' => 'BAHAGIAN PELESENAN',
                'agn_namargks' => 'BPLN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 17,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'BPKN',
                'agn_namaagensi' => 'BAHAGIAN PENGUATKUASAAN',
                'agn_namargks' => 'BPKN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 18,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'KKM',
                'agn_namaagensi' => 'KEMENTERIAN KESIHATAN MALAYSIA',
                'agn_namargks' => 'KKM',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 19,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'MKN',
                'agn_namaagensi' => 'MAJLIS KESELAMATAN NEGARA',
                'agn_namargks' => 'MKN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'ATL',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 20,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JPBD',
                'agn_namaagensi' => 'JABATAN PERANCANG BANDAR DAN DESA',
                'agn_namargks' => 'JPBD',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 21,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JBGN',
                'agn_namaagensi' => 'JABATAN BANGUNAN',
                'agn_namargks' => 'JBGN',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 22,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JK',
                'agn_namaagensi' => 'JABATAN KEJURUTERAAN',
                'agn_namargks' => 'JK',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
            [
                'id' => 23,
                'agn_idpbt' => 'PRK_MDTM',
                'agn_kodagensi' => 'JKS',
                'agn_namaagensi' => 'JABATAN KESIHATAN',
                'agn_namargks' => 'JKS',
                'agn_areazon' => '00001',
                'agn_katgori' => 'BTD',
                'agn_statf' => 'A',
                'agn_idate' => '2025-12-25 00:00:00',
                'agn_udate' => null,
                'agn_iuser' => 'CSM_ZUBAIRI',
                'agn_uuser' => null,
            ],
        ]);
    }
}
