<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodDokumenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_dokumen')->insert([
            [
                'id' => 1,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 2,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 3,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 4,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 5,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 6,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '07',
                'doc_docdesc' => 'PELAN LOKASI PREMIS',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 7,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '08',
                'doc_docdesc' => 'PELAN LANTAI PREMIS',
                'doc_catatan' => 'Menunjukkan susun atur ruang, pintu masuk, dapur, tandas (jika berkaitan)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 8,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '09',
                'doc_docdesc' => 'SIJIL LAYAK MENDUDUKI (CF/CCC)',
                'doc_catatan' => 'Jika melibatkan bangunan baharu atau yang diwajibkan oleh MDTM',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 9,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '10',
                'doc_docdesc' => 'SURAT SOKONGAN AGENSI TEKNIKAL LUAR (ATL)',
                'doc_catatan' => 'wajib untuk premis makanan,kilang,setor dan premis berisiko kebakaran',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 10,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '11',
                'doc_docdesc' => 'LAPORAN PEMERIKSAAN KESIHATAN / KEBERSIHAN PREMIS',
                'doc_catatan' => 'Untuk premis makanan & minuman',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 11,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '12',
                'doc_docdesc' => 'SIJIL LATIHAN PENGENDALIAN MAKANAN',
                'doc_catatan' => 'semua pengendali makanan',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 12,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '13',
                'doc_docdesc' => 'SUNTIKAN ANTI-TIFOID',
                'doc_catatan' => 'untuk pengendali makanan',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 13,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '14',
                'doc_docdesc' => 'SURAT KELULUSAN / SOKONGAN JABATAN PERHIDMATAN VETERINAR',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 14,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '15',
                'doc_docdesc' => 'SURAT JABATAN ALAM SEKITAR',
                'doc_catatan' => 'Jika melibatkan sisa, bunyi, bahan kimia dll',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 15,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '16',
                'doc_docdesc' => 'KELULUSAN / PENDAFTARAN KPDN',
                'doc_catatan' => 'Barang kawalan, timbang sukat, francais dll',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 16,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '17',
                'doc_docdesc' => 'RESIT BAYARAN FI PERMOHONAN LESEN',
                'doc_catatan' => 'Kadar bergantung kepada jenis lesen & tempoh (1 tahun / sementara)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 17,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 18,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 19,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 20,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 21,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 22,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 23,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 24,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '07',
                'doc_docdesc' => 'PELAN LOKASI PREMIS',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 25,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '08',
                'doc_docdesc' => 'PELAN LANTAI PREMIS',
                'doc_catatan' => 'Menunjukkan susun atur ruang, pintu masuk, dapur, tandas (jika berkaitan)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 26,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '09',
                'doc_docdesc' => 'SIJIL LAYAK MENDUDUKI (CF/CCC)',
                'doc_catatan' => 'Jika melibatkan bangunan baharu atau yang diwajibkan oleh MDTM',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 27,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '10',
                'doc_docdesc' => 'SURAT SOKONGAN AGENSI TEKNIKAL LUAR (ATL)',
                'doc_catatan' => 'wajib untuk premis makanan,kilang,setor dan premis berisiko kebakaran',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 28,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '11',
                'doc_docdesc' => 'LAPORAN PEMERIKSAAN KESIHATAN / KEBERSIHAN PREMIS',
                'doc_catatan' => 'Untuk premis makanan & minuman',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 29,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '12',
                'doc_docdesc' => 'SIJIL LATIHAN PENGENDALIAN MAKANAN',
                'doc_catatan' => 'semua pengendali makanan',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 30,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '13',
                'doc_docdesc' => 'SUNTIKAN ANTI-TIFOID',
                'doc_catatan' => 'untuk pengendali makanan',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 31,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '14',
                'doc_docdesc' => 'SURAT KELULUSAN / SOKONGAN JABATAN PERHIDMATAN VETERINAR',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 32,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '15',
                'doc_docdesc' => 'SURAT JABATAN ALAM SEKITAR',
                'doc_catatan' => 'Jika melibatkan sisa, bunyi, bahan kimia dll',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 33,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '16',
                'doc_docdesc' => 'KELULUSAN / PENDAFTARAN KPDN',
                'doc_catatan' => 'Barang kawalan, timbang sukat, francais dll',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 34,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '17',
                'doc_docdesc' => 'RESIT BAYARAN FI PERMOHONAN LESEN',
                'doc_catatan' => 'Kadar bergantung kepada jenis lesen & tempoh (1 tahun / sementara)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 35,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 36,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 37,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 38,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 39,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 40,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 41,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '07',
                'doc_docdesc' => 'PELAN LOKASI PREMIS',
                'doc_catatan' => null,
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 42,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '08',
                'doc_docdesc' => 'PELAN LANTAI PREMIS',
                'doc_catatan' => 'Menunjukkan susun atur ruang, pintu masuk, dapur, tandas (jika berkaitan)',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 43,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '09',
                'doc_docdesc' => 'SIJIL LAYAK MENDUDUKI (CF/CCC)',
                'doc_catatan' => 'Jika melibatkan bangunan baharu atau yang diwajibkan oleh MDTM',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 44,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '10',
                'doc_docdesc' => 'SURAT SOKONGAN AGENSI TEKNIKAL LUAR (ATL)',
                'doc_catatan' => 'wajib untuk premis makanan,kilang,setor dan premis berisiko kebakaran',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 45,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '11',
                'doc_docdesc' => 'LAPORAN PEMERIKSAAN KESIHATAN / KEBERSIHAN PREMIS',
                'doc_catatan' => 'Untuk premis makanan & minuman',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 46,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '12',
                'doc_docdesc' => 'SIJIL LATIHAN PENGENDALIAN MAKANAN',
                'doc_catatan' => 'semua pengendali makanan',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 47,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '13',
                'doc_docdesc' => 'SUNTIKAN ANTI-TIFOID',
                'doc_catatan' => 'untuk pengendali makanan',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 48,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '14',
                'doc_docdesc' => 'SURAT KELULUSAN / SOKONGAN JABATAN PERHIDMATAN VETERINAR',
                'doc_catatan' => null,
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 49,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '15',
                'doc_docdesc' => 'SURAT JABATAN ALAM SEKITAR',
                'doc_catatan' => 'Jika melibatkan sisa, bunyi, bahan kimia dll',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 50,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '16',
                'doc_docdesc' => 'KELULUSAN / PENDAFTARAN KPDN',
                'doc_catatan' => 'Barang kawalan, timbang sukat, francais dll',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 51,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '17',
                'doc_docdesc' => 'RESIT BAYARAN FI PERMOHONAN LESEN',
                'doc_catatan' => 'Kadar bergantung kepada jenis lesen & tempoh (1 tahun / sementara)',
                'doc_statusd' => 'P',
                'doc_statf' => 'A',
                'doc_jenismhn' => 'B',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 52,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 53,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 54,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 55,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 56,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 57,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'P',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 58,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 59,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 60,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 61,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 62,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 63,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 64,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '07',
                'doc_docdesc' => 'PELAN LOKASI PREMIS',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 65,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '08',
                'doc_docdesc' => 'PELAN LANTAI PREMIS',
                'doc_catatan' => 'Menunjukkan susun atur ruang, pintu masuk, dapur, tandas (jika berkaitan)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 66,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '09',
                'doc_docdesc' => 'SIJIL LAYAK MENDUDUKI (CF/CCC)',
                'doc_catatan' => 'Jika melibatkan bangunan baharu atau yang diwajibkan oleh MDTM',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 67,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '10',
                'doc_docdesc' => 'SURAT SOKONGAN AGENSI TEKNIKAL LUAR (ATL)',
                'doc_catatan' => 'wajib untuk premis makanan,kilang,setor dan premis berisiko kebakaran',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 68,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '11',
                'doc_docdesc' => 'LAPORAN PEMERIKSAAN KESIHATAN / KEBERSIHAN PREMIS',
                'doc_catatan' => 'Untuk premis makanan & minuman',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 69,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '12',
                'doc_docdesc' => 'SIJIL LATIHAN PENGENDALIAN MAKANAN',
                'doc_catatan' => 'semua pengendali makanan',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 70,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '13',
                'doc_docdesc' => 'SUNTIKAN ANTI-TIFOID',
                'doc_catatan' => 'untuk pengendali makanan',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 71,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '14',
                'doc_docdesc' => 'SURAT KELULUSAN / SOKONGAN JABATAN PERHIDMATAN VETERINAR',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 72,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '15',
                'doc_docdesc' => 'SURAT JABATAN ALAM SEKITAR',
                'doc_catatan' => 'Jika melibatkan sisa, bunyi, bahan kimia dll',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 73,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '16',
                'doc_docdesc' => 'KELULUSAN / PENDAFTARAN KPDN',
                'doc_catatan' => 'Barang kawalan, timbang sukat, francais dll',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 74,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'T',
                'doc_kddocmt' => '17',
                'doc_docdesc' => 'RESIT BAYARAN FI PERMOHONAN LESEN',
                'doc_catatan' => 'Kadar bergantung kepada jenis lesen & tempoh (1 tahun / sementara)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 75,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '01',
                'doc_docdesc' => 'BORANG PERMOHONAN LESEN PERNIAGAAN',
                'doc_catatan' => 'Diisi lengkap & ditandatangani pemohon',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 76,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '02',
                'doc_docdesc' => 'SALINAN KAD PENGENALAN',
                'doc_catatan' => 'Pemilik / rakan kongsi / pengarah',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 77,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '03',
                'doc_docdesc' => 'GAMBAR UKURAN PASPORT',
                'doc_catatan' => '1¿2 keping (bergantung borang)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 78,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '04',
                'doc_docdesc' => 'SALINAN SURUHANJAYA SYARIKAT MALAYSIA (SSM)',
                'doc_catatan' => 'Borang D / Sijil Pendaftaran Perniagaan (Enterprise).  Borang 9 / 13 / Sijil Pemerbadanan (Sdn. Bhd.)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 79,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '05',
                'doc_docdesc' => 'SALINAN PERJANJIAN SEWA /  GERAN HAKMILIK PREMIS',
                'doc_catatan' => 'Perjanjian sewa yang sah.  Geran tanah/bangunan jika milik sendiri',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 80,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '06',
                'doc_docdesc' => 'CUKAI TAKSIRAN TERKINI',
                'doc_catatan' => 'Resit bayaran terkini.',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 81,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '07',
                'doc_docdesc' => 'PELAN LOKASI PREMIS',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 82,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '08',
                'doc_docdesc' => 'PELAN LANTAI PREMIS',
                'doc_catatan' => 'Menunjukkan susun atur ruang, pintu masuk, dapur, tandas (jika berkaitan)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 83,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '09',
                'doc_docdesc' => 'SIJIL LAYAK MENDUDUKI (CF/CCC)',
                'doc_catatan' => 'Jika melibatkan bangunan baharu atau yang diwajibkan oleh MDTM',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 84,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '10',
                'doc_docdesc' => 'SURAT SOKONGAN AGENSI TEKNIKAL LUAR (ATL)',
                'doc_catatan' => 'wajib untuk premis makanan,kilang,setor dan premis berisiko kebakaran',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 85,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '11',
                'doc_docdesc' => 'LAPORAN PEMERIKSAAN KESIHATAN / KEBERSIHAN PREMIS',
                'doc_catatan' => 'Untuk premis makanan & minuman',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 86,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '12',
                'doc_docdesc' => 'SIJIL LATIHAN PENGENDALIAN MAKANAN',
                'doc_catatan' => 'semua pengendali makanan',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 87,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '13',
                'doc_docdesc' => 'SUNTIKAN ANTI-TIFOID',
                'doc_catatan' => 'untuk pengendali makanan',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 88,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '14',
                'doc_docdesc' => 'SURAT KELULUSAN / SOKONGAN JABATAN PERHIDMATAN VETERINAR',
                'doc_catatan' => null,
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 89,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '15',
                'doc_docdesc' => 'SURAT JABATAN ALAM SEKITAR',
                'doc_catatan' => 'Jika melibatkan sisa, bunyi, bahan kimia dll',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 90,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '16',
                'doc_docdesc' => 'KELULUSAN / PENDAFTARAN KPDN',
                'doc_catatan' => 'Barang kawalan, timbang sukat, francais dll',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
            [
                'id' => 91,
                'doc_idpbt' => 'PRK_MDTM',
                'doc_ktegori' => 'K',
                'doc_kddocmt' => '17',
                'doc_docdesc' => 'RESIT BAYARAN FI PERMOHONAN LESEN',
                'doc_catatan' => 'Kadar bergantung kepada jenis lesen & tempoh (1 tahun / sementara)',
                'doc_statusd' => 'M',
                'doc_jenismhn' => 'P',
                'doc_idate' => '2025-12-25 00:00:00',
                'doc_udate' => null,
                'doc_iuser' => 'CSM_ZUBAIRI',
                'doc_uuser' => null,
            ],
        ]);
    }
}
