<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodAktakompaunSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_aktakompaun')->insert([
            [
                'id' => 1,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'P01',
                'akt_trikhlulus' => '2003-04-14 00:00:00',
                'akt_keterangn' => 'PERINTAH PENGANGKUTAN JALAN (PERUNTUKAN TEMPAT LETAK KERETA) (MDTM) 2003',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 2,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U01',
                'akt_trikhlulus' => '1984-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PENJAJA (MDTM) 1984',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 3,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U02',
                'akt_trikhlulus' => '1982-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PELESENAN TRED, PERNIAGAAN DAN PERINDUSTRIAN (MDTM) 1986',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 4,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U03',
                'akt_trikhlulus' => '2015-11-23 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL IKLAN (MDTM) 2015',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 5,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U04',
                'akt_trikhlulus' => '1983-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PENGENDALIAN MAKANAN 1983',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 6,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'A02',
                'akt_trikhlulus' => '1974-01-01 00:00:00',
                'akt_keterangn' => 'AKTA JALAN, PARIT DAN BANGUNAN 1974',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 7,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U06',
                'akt_trikhlulus' => '2007-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PEMUNGUTAN, PEMBUANGAN DAN PELUPUSAN SAMPAH-SARAP (MDTM) 2007',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 8,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U07',
                'akt_trikhlulus' => '2007-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PASAR (MDTM) 2007',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 9,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U08',
                'akt_trikhlulus' => '1990-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL HAIWAN MERAYAU (MDTM) 1990',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 10,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U12',
                'akt_trikhlulus' => '1992-01-01 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL TAMAN (MDTM) 1986',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 11,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'A01',
                'akt_trikhlulus' => '1976-01-01 00:00:00',
                'akt_keterangn' => 'AKTA KERAJAAN TEMPATAN 1976',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 12,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U21',
                'akt_trikhlulus' => '2003-10-09 00:00:00',
                'akt_keterangn' => 'UNDANG-UNDANG KECIL PELESENAN ANJING (MDTM) 2005',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 13,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'U22',
                'akt_trikhlulus' => '2020-07-07 00:00:00',
                'akt_keterangn' => 'UUK PELESENAN TRED PERNIAGAAN DAN PERINDUSTRIAN MDTM 2017',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
            [
                'id' => 14,
                'akt_idpbt' => 'PRK_MDTM',
                'akt_kodakta' => 'A03',
                'akt_trikhlulus' => '2020-01-02 00:00:00',
                'akt_keterangn' => 'AKTA PENGANGKUTAN JALAN 1987',
                'akt_idate' => '2025-12-19 00:00:00',
                'akt_udate' => null,
                'akt_iuser' => 'zubairi',
                'akt_uuser' => null,
            ],
        ]);
    }
}
