<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodJenisaduanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_jenisaduan')->insert([
            [
                'id' => 1,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '05',
                'kat_keterangan' => 'TANAH BERLOPAK',
                'kat_kataduan' => 'E',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 2,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '03',
                'kat_keterangan' => 'BANTAHAN',
                'kat_kataduan' => 'E',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 3,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'PERNIAGAAN',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 4,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '02',
                'kat_keterangan' => 'GERAI',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 5,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '03',
                'kat_keterangan' => 'GANGGUAN BINATANG',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 6,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '04',
                'kat_keterangan' => 'GANGGUAN SERANGGA',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 7,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '05',
                'kat_keterangan' => 'GANGGUAN',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 8,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '06',
                'kat_keterangan' => 'HALANGAN',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 9,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '07',
                'kat_keterangan' => 'SEMAK-SAMUN',
                'kat_kataduan' => 'A',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 10,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'JALAN',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 11,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '02',
                'kat_keterangan' => 'PARIT/LONGKANG',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 12,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '03',
                'kat_keterangan' => 'LAMPU JALAN/TRAFIK',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 13,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '04',
                'kat_keterangan' => 'PAPAN TANDA',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 14,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '05',
                'kat_keterangan' => 'PADANG PERMAINAN/AWAM',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 15,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '06',
                'kat_keterangan' => 'DEWAN KOTOR',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 16,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '07',
                'kat_keterangan' => 'TEMPAT LETAK KERETA',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 17,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'PEMBINAAN PERUMAHAN/BANGUNAN',
                'kat_kataduan' => 'C',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 18,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '02',
                'kat_keterangan' => 'KENDERAAN BERAT',
                'kat_kataduan' => 'C',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 19,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '03',
                'kat_keterangan' => 'BANGUNAN',
                'kat_kataduan' => 'C',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 20,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'SAMPAH',
                'kat_kataduan' => 'D',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 21,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '02',
                'kat_keterangan' => 'LONGKANG',
                'kat_kataduan' => 'D',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 22,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '03',
                'kat_keterangan' => 'BAHU JALAN',
                'kat_kataduan' => 'D',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 23,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '04',
                'kat_keterangan' => 'POKOK',
                'kat_kataduan' => 'D',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 24,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'BENCANA ALAM',
                'kat_kataduan' => 'E',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 25,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '02',
                'kat_keterangan' => 'ADUAN DALAMAN',
                'kat_kataduan' => 'E',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 26,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '04',
                'kat_keterangan' => 'PAGAR',
                'kat_kataduan' => 'E',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 27,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'ADUAN TIDAK DIAMBIL TINDAKAN',
                'kat_kataduan' => 'F',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 28,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '01',
                'kat_keterangan' => 'PEGAWAI 123 (TEST SISTEM)',
                'kat_kataduan' => 'P',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 29,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '12',
                'kat_keterangan' => 'ROSAK',
                'kat_kataduan' => 'G',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 30,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '05',
                'kat_keterangan' => 'ICT',
                'kat_kataduan' => 'D',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
            [
                'id' => 31,
                'kat_idpbt' => 'PRK_MDTM',
                'kat_kodjenisaduan' => '08',
                'kat_keterangan' => 'PREMIS SEWAAN MDTM',
                'kat_kataduan' => 'B',
                'kat_ptjpk' => null,
                'kat_piagam' => 10,
                'kat_statf' => 'Y',
                'kat_idate' => '2025-12-25 00:00:00',
                'kat_udate' => null,
                'kat_iuser' => 'CSM_ZUBAIRI',
                'kat_uuser' => null,
            ],
        ]);
    }
}
