<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OscKodPtjpkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('osc_kod_ptjpk')->insert([
            [
                'id' => 1,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0100',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'YANG DIPERTUA',
                'ptj_namarngks' => 'YANG DIPERTUA',
                'ptj_nopegawai' => '10529',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 2,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0700',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'UNIT AUDIT DALAM',
                'ptj_namarngks' => 'UNIT AUDIT DALAM',
                'ptj_nopegawai' => '10264',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 3,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1101',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'UNIT PUSAT SETEMPAT',
                'ptj_namarngks' => 'UNIT OSC',
                'ptj_nopegawai' => '10528',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 4,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1201',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN PENGUATKUASAAN',
                'ptj_namarngks' => 'BHG PNGUATKUASA',
                'ptj_nopegawai' => '10259',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 5,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1200',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN PENGUATKUASAAN',
                'ptj_namarngks' => 'J PENGUATKUASA ',
                'ptj_nopegawai' => '10259',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 6,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1300',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'RUMAH REHAT',
                'ptj_namarngks' => 'RUMAH REHAT',
                'ptj_nopegawai' => '10317',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 7,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0200',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN PERBENDAHARAAN',
                'ptj_namarngks' => 'PERBENDAHARAAN',
                'ptj_nopegawai' => '10315',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 8,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0101',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN PENTADBIRAN DAN PERKHIDMATAN',
                'ptj_namarngks' => 'BHG PENTADBIRAN',
                'ptj_nopegawai' => '10317',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 9,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0300',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN PENILAIAN DAN PENGURUSAN HARTA',
                'ptj_namarngks' => 'JBT PENILAIAN/HARTA',
                'ptj_nopegawai' => '10160',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 10,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0800',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'UNIT UNDANG-UNDANG',
                'ptj_namarngks' => 'UNIT UNDANG-UNDANG',
                'ptj_nopegawai' => '10486',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 11,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0500',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN KEJURUTERAAN',
                'ptj_namarngks' => 'JBT KEJURUTERAAN',
                'ptj_nopegawai' => '10197',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 12,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0600',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN PERBANDARAN DAN KESIHATAN',
                'ptj_namarngks' => 'JBT PERBANDARAN',
                'ptj_nopegawai' => '10176',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 13,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0501',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN KEJURUTERAAN',
                'ptj_namarngks' => 'BHG KEJURUTERAAN',
                'ptj_nopegawai' => '10197',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 14,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0400',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'JABATAN PERANCANGAN PEMBANGUNAN',
                'ptj_namarngks' => 'JBT PERANCANGAN',
                'ptj_nopegawai' => '10352',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 15,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0401',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN PERANCANGAN PEMBANGUNAN',
                'ptj_namarngks' => 'BHG PERANCANG BANDAR',
                'ptj_nopegawai' => '10352',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 16,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0801',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'UNIT UNDANG-UNDANG',
                'ptj_namarngks' => 'UNIT UNDANG-UNDANG',
                'ptj_nopegawai' => '10486',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 17,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0301',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN PENILAIAN',
                'ptj_namarngks' => 'BHG PENILAIAN',
                'ptj_nopegawai' => '10160',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 18,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0201',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN KEWANGAN DAN AKAUN',
                'ptj_namarngks' => 'BHG KEWANGAN',
                'ptj_nopegawai' => '10315',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 19,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0601',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'BAHAGIAN PERBANDARAN DAN KEBERSIHAN',
                'ptj_namarngks' => 'BAHAGIAN PERBANDARAN',
                'ptj_nopegawai' => '10012',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 20,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1100',
                'ptj_ptjpkkelas' => '1',
                'ptj_ptjpknama' => 'UNIT ONE STOP CENTER',
                'ptj_namarngks' => 'UNIT OSC',
                'ptj_nopegawai' => '10528',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 21,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0102',
                'ptj_ptjpkkelas' => '3',
                'ptj_ptjpknama' => 'BAHAGIAN TEKNOLOGI MAKLUMAT',
                'ptj_namarngks' => 'BHG T/MAKLUMAT',
                'ptj_nopegawai' => '10244',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 22,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0103',
                'ptj_ptjpkkelas' => '3',
                'ptj_ptjpknama' => 'BAHAGIAN PENGUATKUASAAN',
                'ptj_namarngks' => 'BHG PENGUATKUASA',
                'ptj_nopegawai' => '10227',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 23,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0602',
                'ptj_ptjpkkelas' => '3',
                'ptj_ptjpknama' => 'BAHAGIAN PELESENAN DAN KESIHATAN AM',
                'ptj_namarngks' => 'BHG PELESENAN',
                'ptj_nopegawai' => '10176',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 24,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '1301',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'UNIT RUMAH REHAT TG MALIM /SLIM RIVER',
                'ptj_namarngks' => 'UNIT RUMAH REHAT',
                'ptj_nopegawai' => '10137',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 25,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0701',
                'ptj_ptjpkkelas' => '2',
                'ptj_ptjpknama' => 'UNIT AUDIT DALAM',
                'ptj_namarngks' => 'UNIT AUDIT DALAM',
                'ptj_nopegawai' => '10264',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
            [
                'id' => 26,
                'ptj_idpbt' => 'PRK_MDTM',
                'ptj_ptjpkcode' => '0402',
                'ptj_ptjpkkelas' => '3',
                'ptj_ptjpknama' => 'UNIT LANDSKAP',
                'ptj_namarngks' => 'UNIT LANDSKAP',
                'ptj_nopegawai' => '10347',
                'ptj_idate' => '2025-12-25 00:00:00',
                'ptj_udate' => null,
                'ptj_iuser' => 'CSM_ZUBAIRI',
                'ptj_uuser' => null,
            ],
        ]);
    }
}
